require 'bundler'
# For Bundler.with_clean_env
require 'bundler/setup'

TRAVELING_RUBY_VERSION = "20150715-2.2.2".freeze
NOKOGIRI_VERSION = "1.6.6.2".freeze  # Must match Gemfile
HPRICOT_PACKAGE_NAME = "hpricot-0.8.6.tar.gz".freeze

desc "Package your app"
task :package => ['package:linux:x86_64']

namespace :package do
  namespace :linux do
    desc "Package your app for Linux x86_64"
    task :x86_64 => [:bundle_install,
      "traveling-ruby-#{TRAVELING_RUBY_VERSION}-linux-x86_64.tar.gz",
      "traveling-ruby-#{TRAVELING_RUBY_VERSION}-linux-x86_64-nokogiri-#{NOKOGIRI_VERSION}.tar.gz",
      HPRICOT_PACKAGE_NAME
    ] do
      create_package("linux-x86_64")
    end
  end

  desc "Install gems to local directory"
  task :bundle_install do
    if RUBY_VERSION !~ /^2\.2\./
      abort "You can only 'bundle install' using Ruby 2.2, because that's what Traveling Ruby uses."
    end
    sh "rm -rf tmp"
    sh "mkdir tmp"
    sh "cp ruby/Gemfile ruby/Gemfile.lock tmp/"

    Bundler.with_clean_env do
      sh "cd tmp && env BUNDLE_IGNORE_CONFIG=1 bundle install --path ../vendor --without development"
    end

    sh "rm -rf tmp"
    sh "rm -f vendor/*/*/cache/*"
    sh "rm -rf vendor/ruby/*/extensions"
    sh "find vendor/ruby/*/gems -name '*.so' | xargs rm -f"
    sh "find vendor/ruby/*/gems -name '*.bundle' | xargs rm -f"
    sh "find vendor/ruby/*/gems -name '*.o' | xargs rm -f"
  end
end

file "traveling-ruby-#{TRAVELING_RUBY_VERSION}-linux-x86_64.tar.gz" do
  download_runtime("linux-x86_64")
end

file "traveling-ruby-#{TRAVELING_RUBY_VERSION}-linux-x86_64-nokogiri-#{NOKOGIRI_VERSION}.tar.gz" do
  download_native_extension("linux-x86_64", "nokogiri-#{NOKOGIRI_VERSION}")
end

file HPRICOT_PACKAGE_NAME do
  sh "curl -L --fail -o #{HPRICOT_PACKAGE_NAME} " +
    "https://raw.githubusercontent.com/j-sakamoto/ruby-2.2.2-extensions/master/x86_64-linux/#{HPRICOT_PACKAGE_NAME}"
end

def create_package(target)
  sh "mkdir -p lib"
  sh "rm -rf lib/ruby"
  sh "rm -rf lib/vendor"
  sh "cp -r ruby/ lib/"
  sh "mkdir lib/ruby"
  sh "mkdir lib/vendor"
  sh "tar -xzf traveling-ruby-#{TRAVELING_RUBY_VERSION}-#{target}.tar.gz -C lib/ruby"
  sh "rm traveling-ruby-#{TRAVELING_RUBY_VERSION}-#{target}.tar.gz"
  sh "mv vendor lib"
  sh "cp ruby/Gemfile ruby/Gemfile.lock lib/vendor/"
  sh "mkdir lib/vendor/.bundle"
  sh "cp ruby/.bundle/config lib/vendor/.bundle/config"
  sh "tar -xzf traveling-ruby-#{TRAVELING_RUBY_VERSION}-#{target}-nokogiri-#{NOKOGIRI_VERSION}.tar.gz " +
    "-C lib/vendor/ruby"
  sh "rm traveling-ruby-#{TRAVELING_RUBY_VERSION}-#{target}-nokogiri-#{NOKOGIRI_VERSION}.tar.gz"
  sh "tar -xzf #{HPRICOT_PACKAGE_NAME} -C lib/vendor/ruby"
  sh "rm #{HPRICOT_PACKAGE_NAME}"
end

def download_runtime(target)
  sh "curl -L -O --fail " +
    "http://d6r77u77i8pq3.cloudfront.net/releases/traveling-ruby-#{TRAVELING_RUBY_VERSION}-#{target}.tar.gz"
end

def download_native_extension(target, gem_name_and_version)
  sh "curl -L --fail -o traveling-ruby-#{TRAVELING_RUBY_VERSION}-#{target}-#{gem_name_and_version}.tar.gz " +
    "http://d6r77u77i8pq3.cloudfront.net/releases/traveling-ruby-gems-#{TRAVELING_RUBY_VERSION}-#{target}/#{gem_name_and_version}.tar.gz"
end
