# frozen_string_literal: true
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'html2haml'
gem 'html2slim'
gem 'nokogiri', "1.6.6.2"
gem 'hpricot', "0.8.6"
